microsoft/codeql

csharp/ql/lib/semmle/code/csharp/security/dataflow/ZipSlipQuery.qll
csharp/ql/src/Security Features/CWE-022/ZipSlip.qhelp
csharp/ql/src/Security Features/CWE-022/ZipSlip.ql
csharp/ql/test/query-tests/Security Features/CWE-022/ZipSlip/ZipSlip.cs
csharp/ql/test/query-tests/Security Features/CWE-022/ZipSlip/ZipSlip.expected

+ Patched False negative case with original GH query (see bottom of post)
+ Patched False positive case with sanitizer wrappers (see below code example)
+ Declares String concatenation as an unsanitized path combination vector
+ Declares String interpolation as an unsanitized path combination vector
+ Creates a class `AbstractWrapperSanitizerMethod` which identifies the set of methods which act as a more restrictive subset of `System.String.StartsWith` which then acts as a SanitizerGuard.
+ Various helper subclasses / alias classes
+ Patched False negative case with original GH query
An AbstractWrapperSanitizerMethod is a Method where
- The Method has a MethodCall to a given class of Sanitizers
- The Method can /only/ return true if it first passes through the RootSanitizerGuard
- Or if …

CWE-022 C# ZipSlip Improvements

---

csharp/ql/lib/semmle/code/csharp/security/dataflow/ZipSlipQuery.qll
csharp/ql/src/Security Features/CWE-022/ZipSlip.ql

Reverts ZipSlip to upstream.
Performance issues in `csharp\Security Features\CWE-022\ZipSlip.ql` are preventing analysis. Upstream performs in relatively linear memory patterns.
Will follow up with a true fix in PR to upstream + when ready, open another PR here.

Revert Zipslip to upstream

---

shared/dataflow/codeql/dataflow/DataFlow.qll

Upgrades the shared DataFlow library to include the following predicates in the signature for a PathNode:
- getNode()
- getASuccessor()
- isSource()

Upgrade Shared DataFlow PathNode Signature

---

java/ql/lib/semmle/code/java/security/TempDirLocalInformationDisclosureQuery.qll

Adds isSource to the PathNode class in MethodCallInsecureFileCreation which is a single-step PathNode.

MethodCallInsecureFileCreation isSource

---

cpp/ql/src/Critical/DoubleFree.ql
cpp/ql/src/Critical/FlowAfterFree.qll
cpp/ql/src/Critical/UseAfterFree.ql
cpp/ql/test/query-tests/Critical/MemoryFreed/DoubleFree.expected
cpp/ql/test/query-tests/Critical/MemoryFreed/UseAfterFree.expected

@bdrodes these are my suggestions to https://github.com/github/codeql/pull/15343.
Commit-by-commit review recommended - especially if you're not yet comfortable with parameterized modules!
- The first commit does a straightforward refactoring of the interface of `FlowFromFree`: instead of passing two predicates as parameters to the module I wrap the "input predicates" into a module signature and change the `FlowFromFree` module to take such an "input module" as a parameter.
- The next commit is really the meat of my suggestion: it adds a new predicate to the "input module" that represents additional requirements on the relationship between the source and the sink. In particular, for the github/codeql queries this can be the dominance/post-domination relationship, and for microsoft/codeql …

C++: Suggestions to #15343

---

cpp/ql/lib/semmle/code/cpp/security/flowafterfree/FlowAfterFree.qll
cpp/ql/lib/semmle/code/cpp/security/flowafterfree/UseAfterFree.qll

@bdrodes this should hopefully fix the CI errors on https://github.com/github/codeql/pull/15343 🤞

C++: Make more entities `private` and add QLDoc to public predicates

---

csharp/ql/lib/semmle/code/csharp/dataflow/DataFlowStack.qll
java/ql/lib/semmle/code/java/dataflow/DataFlowStack.qll
shared/dataflowstack/codeql/dataflowstack/DataFlowStack.qll
shared/dataflowstack/qlpack.yml

Fills in missing type parameter introduced into the common DataFlow library for DataFlowStack

DFS CPP + Java Compile Error patch

---

csharp/ql/lib/semmle/code/csharp/security/dataflow/ZipSlipQuery.qll
csharp/ql/test/query-tests/Security Features/CWE-022/ZipSlip/ZipSlip.cs

Re-reverts ZipSlip query with a performance patch, fixing several false positives as well as false negative cases.
Performance tested on 2GB DB.
Original (Upstream): 8145s
Unoptimized: 15232s
Optimized: 8846s.

Zipslip performance fix

---

csharp/ql/src/Security Features/CWE-327/InsecureSQLConnection.ql

Encrypt is true by default in versions 4.0+ , so if the class is from that version or later, doesn't need to explicitly specify encrypt as true.
https://learn.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient.sqlconnectionstringbuilder.encrypt?view=sqlclient-dotnet-standard-5.2

Update to insecure sql connection to check for version

---

csharp/ql/lib/semmle/code/csharp/commons/ComparisonTest.qll
csharp/ql/lib/semmle/code/csharp/exprs/Call.qll
csharp/ql/lib/semmle/code/csharp/security/dataflow/ZipSlipQuery.qll

This PR fixes a bad join order in `cs/zipslip`. @LWSimpkins was kind enough to provide me with a log file that showed the problematic predicate:
```
Starting to evaluate predicate _Call::Call.getArgument/1#dispred#28f02664#bff_102#join_rhs_params#join_rhs/3@b06f61j1
[2024-08-08 19:32:06] (876s) Sequence stamp origin is -6152927877850464690
[2024-08-08 19:32:06] (876s) Pausing evaluation to evict 4.11GiB ARRAYS at sequence stamp o+0
[2024-08-08 19:32:07] (876s) Unpausing evaluation: 102.98GiB forgotten: 102.98GiB UNREACHABLE (115351 items up to o+-2)
[2024-08-08 19:34:34] (1023s) Pausing evaluation to evict 4.11GiB ARRAYS at sequence stamp o+169351
[2024-08-08 19:34:34] (1023s) Unpausing evaluation: 88.81GiB forgotten: 88.81GiB UNREACHABLE (78441 items up to o+169348)
[2024-08-08 19:36:27] …
```

C#: Fix join order in `cs/zipslip`

---

powershell/ql/src/experimental/CommandInjection.ql
powershell/ql/src/qlpack.yml

This PR moves the final piece of QL-for-Powershell code from the internal repo to the public one: an experimental query.
Once this is merged we should be able to get rid of the internal stuff

PS: Port `powershell/command-injection` from the internal repo

---

powershell/downgrades/d8eb95bd91979583b569cdd50de46c59210f2aa9/old.dbscheme
powershell/downgrades/d8eb95bd91979583b569cdd50de46c59210f2aa9/semmlecode.powershell.dbscheme
powershell/downgrades/d8eb95bd91979583b569cdd50de46c59210f2aa9/upgrade.properties
powershell/ql/lib/qlpack.yml
powershell/ql/lib/semmle/code/powershell/Ast.qll
powershell/ql/lib/semmle/code/powershell/CatchClause.qll
powershell/ql/lib/semmle/code/powershell/Configuration.qll
powershell/ql/lib/semmle/code/powershell/DataStmt.qll
powershell/ql/lib/semmle/code/powershell/DoUntilStmt.qll
powershell/ql/lib/semmle/code/powershell/DoWhileStmt.qll
powershell/ql/lib/semmle/code/powershell/ExitStmt.qll
powershell/ql/lib/semmle/code/powershell/ForEachStmt.qll
powershell/ql/lib/semmle/code/powershell/ForStmt.qll
powershell/ql/lib/semmle/code/powershell/GotoStmt.qll
powershell/ql/lib/semmle/code/powershell/IfStmt.qll
powershell/ql/lib/semmle/code/powershell/ReturnStmt.qll
powershell/ql/lib/semmle/code/powershell/TryStmt.qll
powershell/ql/lib/semmle/code/powershell/WhileStmt.qll
powershell/ql/lib/semmlecode.powershell.dbscheme
powershell/ql/lib/upgrades/40bf985f18b7a9affb0c97d342fa2d43c629b905/old.dbscheme
powershell/ql/lib/upgrades/40bf985f18b7a9affb0c97d342fa2d43c629b905/semmlecode.powershell.dbscheme
powershell/ql/lib/upgrades/40bf985f18b7a9affb0c97d342fa2d43c629b905/upgrade.properties

This PR fixes a couple of small annoyances I've encountered in the Powershell dbscheme. They're all written in the first commit of this PR:
1. Flip the name of the child and parent column for 'parent' to reflect
how this is actually populated by the extractor.
2. Make some of the coumns more specific to the actual data type.
3. Make `@named_attribute_argument` an `@ast` branch.
The remaining commits go through creating a database upgrade script
Commit-by-commit review recommended

PS: Small dbscheme updates

---

powershell/ql/lib/qlpack.yml
powershell/ql/lib/semmle/code/powershell/controlflow/CfgNodes.qll
powershell/ql/lib/semmle/code/powershell/dataflow/DataFlow.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowDispatch.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowImpl.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowImplCommon.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowImplSpecific.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowPrivate.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowPublic.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/TaintTrackingImplSpecific.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/TaintTrackingPrivate.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/TaintTrackingPublic.qll

This adds the skeleton for the dataflow library for Powershell.
Nothing interesting in this PR. I've just copied over Ruby's dataflow library and stripped everything Ruby-related out.

PS: Add dataflow skeleton

---

powershell/ql/consistency-queries/SsaConsistency.ql
powershell/ql/lib/semmle/code/powershell/Variable.qll
powershell/ql/lib/semmle/code/powershell/controlflow/CfgNodes.qll
powershell/ql/lib/semmle/code/powershell/dataflow/Ssa.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/SsaImpl.qll

Just like the shared CFG library that we introduced for Powershell has a useful set of consistency queries, the shared SSA library also comes with a set of consistency queries. This PR exposes these consistency queries.
In addition, this PR also includes the set of SSA reads/writes to be reads and writes to parameters.

PS: Add SSA consistency queries and include parameter read/writes as SSA read/writes

---

powershell/ql/lib/semmle/code/powershell/Function.qll
powershell/ql/lib/semmle/code/powershell/Variable.qll
powershell/ql/lib/semmle/code/powershell/VariableExpression.qll
powershell/ql/lib/semmle/code/powershell/controlflow/CfgNodes.qll
powershell/ql/lib/semmle/code/powershell/dataflow/Ssa.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/SsaImpl.qll
powershell/ql/test/library-tests/ssa/explicit.ps1
powershell/ql/test/library-tests/ssa/parameters.ps1
powershell/ql/test/library-tests/ssa/ssa.expected
powershell/ql/test/library-tests/ssa/ssa.ql

An SSA definition needs to live at some index in a basic block. For a standard write to a local variable this is quite easy: just place the write at the index of the `AssignStmt` that writes to the variable.
In general, every read of an SSA variable needs to have a corresponding (unique) write. And that also includes parameters! So we need to have an initial definition of every parameter.
This PR adds such an initial definition of parameters. Since definition needs to happen before anything else in the function, I've placed the definitions at negative indices in the basic block. So a function such as:
```ps
function f($a, $b, $c) { ... }
```
has the following SSA definitions of the parameters:
- `$a` at index `-3`
- `$b` at index `-2`
- `$c` at index `-1`
this ensures that they're …

PS: Place parameter definitions in the SSA graph

---

powershell/ql/lib/powershell.qll
powershell/ql/lib/semmle/code/powershell/Call.qll
powershell/ql/lib/semmle/code/powershell/Command.qll
powershell/ql/lib/semmle/code/powershell/ErrorExpr.qll
powershell/ql/lib/semmle/code/powershell/InvokeMemberExpression.qll
powershell/ql/lib/semmle/code/powershell/controlflow/CfgNodes.qll
powershell/ql/lib/semmle/code/powershell/controlflow/internal/Scope.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowPrivate.qll
powershell/ql/test/library-tests/ast/Expressions/expressions.ql
powershell/ql/test/library-tests/dataflow/local/test.ps1
powershell/ql/test/library-tests/dataflow/local/test.ql

This PR plugs in the SSA library we added [here](https://github.com/microsoft/codeql/pull/93) into the dataflow library that we added [here](https://github.com/microsoft/codeql/pull/92).
It's all a fairly straightforward copy/paste from Ruby. In the process I also added a new AST class for `ErrorExpr` and created a convenience class for "function calls" that includes both member function calls and non-member function calls.

PS: Integrate SSA computations into dataflow

---

powershell/ql/lib/semmle/code/powershell/AssignmentStatement.qll
powershell/ql/lib/semmle/code/powershell/Call.qll
powershell/ql/lib/semmle/code/powershell/Command.qll
powershell/ql/lib/semmle/code/powershell/CommandBase.qll
powershell/ql/lib/semmle/code/powershell/CommentEntity.qll
powershell/ql/lib/semmle/code/powershell/StringLiteral.qll
powershell/ql/lib/semmle/code/powershell/controlflow/internal/Completion.qll
powershell/ql/lib/semmle/code/powershell/controlflow/internal/ControlFlowGraphImpl.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowPrivate.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowPublic.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/TaintTrackingImplSpecific.qll
powershell/ql/test/TestUtilities/InlineExpectationsTest.qll
powershell/ql/test/TestUtilities/InlineFlowTest.qll
powershell/ql/test/TestUtilities/InlineFlowTestUtil.qll
powershell/ql/test/TestUtilities/internal/InlineExpectationsTestImpl.qll
powershell/ql/test/library-tests/dataflow/params/test.expected
powershell/ql/test/library-tests/dataflow/params/test.ps1
powershell/ql/test/library-tests/dataflow/params/test.ql

This PR instantiates the `InlineExpectationsTest` library which is a key component all languages use to write dataflow library tests.
I'm glad you asked! The motivation for the library is that it should be easy to read library test output, and quickly review if anything has changes. For example, consider a test such as:
```powershell
$x = Source
Sink $x; # there should be flow from line 1
```
we _could_ have a test that looked like:
```ql
import semmle.code.powershell.dataflow.DataFlow
module Config implements DataFlow::ConfigSig {
// ...
}
module Flow = DataFlow::Global<Config>;
from DataFlow::Node source, DataFlow::Node sink
where Flow::flow(source, sink)
select sink, "Flow from $@", source, source.toString()
```
(or something like that.)
But there are some problems with this approach: …

PS: Add `InineExpectationsTest` library for dataflow tests

---

powershell/ql/lib/semmle/code/powershell/controlflow/CfgNodes.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowPrivate.qll

Now that https://github.com/microsoft/codeql/pull/101 added `StmtNode`s to dataflow we can add a couple of really basic dataflow steps. Specifically, this PR adds:
- The dataflow steps offered by the SSA library that we added in https://github.com/microsoft/codeql/pull/97
- Flow from the right-hand side of assignments to the assignment itself (i.e., flow from `42` to `$x = 42`).
There are no changes to expected files since we're still missing CFG for command invocations. I'm hoping that Dilan or Ben will add those soon (hint hint, wink wink 😄)

PS: Add very basic dataflow steps

---

powershell/ql/lib/semmle/code/powershell/MemberExpr.qll
powershell/ql/lib/semmle/code/powershell/controlflow/CfgNodes.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowPrivate.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowPublic.qll
powershell/ql/test/library-tests/dataflow/fields/test.expected
powershell/ql/test/library-tests/dataflow/fields/test.ps1
powershell/ql/test/library-tests/dataflow/fields/test.ql

This PR implements field-based dataflow (i.e., "field flow") for Powershell.
Field flow is what allows us to get flow in examples such as:
```powershell
$x.f = Source
Sink $x.f
```
While it may look innocent, field flow is _extremely_ powerful, and _extremely_ hard to get to perform well. Luckily, all the complications are hidden away inside the shared dataflow library, so all we need to do is:
- Make sure there exists `DataFlow::Node`s to represent the notion of "a dataflow node where we have just stored data into". These nodes are known as "post-update nodes".
- Tell the dataflow library what a write into a field looks like. This is the job of `storeStep`.
- Tell the dataflow library what a read of a field looks like. This is the job of `readStep`.
Consider an example such as: …

PS: Add field flow

---

powershell/ql/lib/semmle/code/powershell/Command.qll
powershell/ql/lib/semmle/code/powershell/Variable.qll
powershell/ql/lib/semmle/code/powershell/controlflow/CfgNodes.qll
powershell/ql/lib/semmle/code/powershell/controlflow/internal/ControlFlowGraphImpl.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowDispatch.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowPrivate.qll
powershell/ql/test/library-tests/dataflow/params/test.ps1

Not gonna lie - this code was actually kinda complex 🙈
This PR implements the logic for matching up arguments and parameters. For Powershell, this is harder than it sounds!
For most languages this is simply an integer: match up (e.g.,) the 3rd argument with the 3rd parameter. However, some languages also allow passing arguments by keyword such as:
```python
def foo(x, y):
print(x, y)
foo(x=1, y=2)
foo(y=2, x=1)
```
Both these calls print `1 2`.
Poweshell has the interesting feature that you can do _both_ in a single call. For example:
```powershell
Function Foo($x, $y) {
Write-Host "$x $y"
}
Foo 1 2
Foo -x 1 -y 2
Foo 2 -x 1
Foo -y 2 1
```
All of these print `1 2`. And now the challenge is to match up the arguments with the right parameter.
DataFlow provides a set of hooks that need to be …

PS: Implement argument/parameter matching in dataflow

---

cpp/ql/src/Security/CWE/CWE-704/WcharCharConversion.ql
cpp/ql/test/query-tests/Security/CWE/CWE-704/WcharCharConversion.cpp
cpp/ql/test/query-tests/Security/CWE/CWE-704/WcharCharConversion.expected

Cherry pick of upstream changes to fix false positives to wcharcharconversion

Wchar fp fixes

---

csharp/ql/lib/semmle/code/csharp/security/dataflow/TaintedPathQuery.qll
csharp/ql/test/query-tests/Security Features/CWE-022/TaintedPath/TaintedPath.cs
csharp/ql/test/query-tests/Security Features/CWE-022/TaintedPath/TaintedPath.expected

The current `cs/path-injection` query explicitly disables `String.StartsWith` and `String.EndsWith` as sanitizers. Presumably because a prefix check such as `path.StartsWith("C:/Foo")` doesn't gurantee that the path points into the `Foo` directory if the path contains `..` (for example, `C:/Foo/../Bar` would satisfy the prefix check, but would point to the `Bar` directory).
However, if the path has been "normalized" (i.e., made absolute) by a call such as `Path.GetFullPath(path)` then no `..` are present in the path, and the `EndsWith` or `StartsWith` checks should be sufficient to avoid path injections.
This PR fixes this by introducing a flow state to represent whether the path is normalized, allowing `StartsWith` and `EndsWith` to act as barriers when the path is in a normalized state. …

C#: Make `StartsWith` and `EndsWith` sanitizers on normalized paths

---

powershell/ql/lib/semmle/code/powershell/Ast.qll
powershell/ql/lib/semmle/code/powershell/Call.qll
powershell/ql/lib/semmle/code/powershell/Function.qll
powershell/ql/lib/semmle/code/powershell/InvokeMemberExpression.qll
powershell/ql/lib/semmle/code/powershell/MemberExpr.qll
powershell/ql/lib/semmle/code/powershell/MemberExpressionBase.qll
powershell/ql/lib/semmle/code/powershell/ScriptBlock.qll
powershell/ql/lib/semmle/code/powershell/Type.qll
powershell/ql/lib/semmle/code/powershell/TypeExpression.qll
powershell/ql/lib/semmle/code/powershell/controlflow/CfgNodes.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowDispatch.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowPrivate.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowPublic.qll
powershell/ql/lib/semmle/code/powershell/typetracking/TypeTracking.qll
powershell/ql/lib/semmle/code/powershell/typetracking/internal/TypeTrackingImpl.qll

This PR implements function call resolution. That is, the mapping from function _calls_ to the set of possible functions that the call may target.
There are two algorithms at play here:
- In order to resolve member function calls we need to compute the runtime type of the qualifier. For example, in order to know where `$x.Foo()` goes we need to know the runtime type of `$x`. We can then look up the `Foo` member function declared by the type that we compute for `$x`.
The runtime type of a qualifier is computed using the shared type-tracking library. There are still quite a lot to be done here, but for now it gets the job done. I will add some more testcases once we have more control-flow so that we actually have some function calls to resolve 😅
- In order to resolve non-member functions we …

PS: Resolve function calls

---

powershell/ql/consistency-queries/DataFlowConsistency.ql
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowPrivate.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/SsaImpl.qll

This adds the dataflow consistency queries for Powershell, and also fixes the worst offenders. In particular, every dataflow node must have an enclosing callable, and I had forgotten to implement this predicate 😅
In addition, Poweshell, unfortunately, needs dataflow nodes for certain statements (because of the structure of the AST), and I had forgotten to include these in SSA.
Both of these problems are fixed in this PR. There are no changes to results because we're still missing loads of control flow.

Powershell: Fix dataflow/SSA consistency errors.

---

powershell/ql/consistency-queries/TypeTrackingConsistency.ql
powershell/ql/lib/powershell.qll
powershell/ql/lib/semmle/code/powershell/Call.qll
powershell/ql/lib/semmle/code/powershell/Command.qll
powershell/ql/lib/semmle/code/powershell/Function.qll
powershell/ql/lib/semmle/code/powershell/InvokeMemberExpression.qll
powershell/ql/lib/semmle/code/powershell/ObjectCreation.qll
powershell/ql/lib/semmle/code/powershell/Type.qll
powershell/ql/lib/semmle/code/powershell/Variable.qll
powershell/ql/lib/semmle/code/powershell/controlflow/CfgNodes.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowDispatch.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowPrivate.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowPublic.qll
powershell/ql/test/library-tests/dataflow/local/test.expected
powershell/ql/test/library-tests/dataflow/typetracking/test.expected
powershell/ql/test/library-tests/dataflow/typetracking/test.ps1
powershell/ql/test/library-tests/dataflow/typetracking/test.ql

This PR adds more type-tracking flow in addition to adding some more tests which for type-tracking which was long overdue 😅
32f7f1b7e440df57518cef5f1473a9e0559c0068 simplifies our AST handling of methods. Previously, we were using two different extensionals to represent functions and methods (i.e., member functions), but I realizied that they're actually _both_ represented by the extensional that we were using for functions. So we could simplify some stuff there 🎉

PS: Add more type-tracking flow

---

powershell/ql/lib/semmle/code/powershell/ConstantExpression.qll
powershell/ql/lib/semmle/code/powershell/Expression.qll
powershell/ql/lib/semmle/code/powershell/IndexExpr.qll
powershell/ql/lib/semmle/code/powershell/VariableExpression.qll
powershell/ql/lib/semmle/code/powershell/controlflow/CfgNodes.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowPrivate.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowPublic.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/TaintTrackingPrivate.qll
powershell/ql/lib/semmle/code/powershell/internal/ExplicitWrite.qll
powershell/ql/lib/semmle/code/powershell/internal/Internal.qll
powershell/ql/lib/semmle/code/powershell/typetracking/internal/TypeTrackingImpl.qll
powershell/ql/test/library-tests/dataflow/fields/test.expected
powershell/ql/test/library-tests/dataflow/fields/test.ps1

In https://github.com/microsoft/codeql/pull/104 we added standard field flow to Powershell for tracking flow through field writes and reads. In this PR, we extend this to also track flow through arrays.
This is a standard thing that is done by almost all CodeQL-supported languages. Specifically, in order to track flow from `Source` to `Sink` in this example:
```powershell
$myArray[5] = Source
...
Sink $myArray[5]
```
we create a new `Content` that represented the number `5` and push `element 5` onto the access path (see [the previous PR](https://github.com/microsoft/codeql/pull/104) for this terminology), which is then read when we later access `$myArray[5]`.
Care must be taken when the offset is unknown in either end. For example, we want flow here:
```powershell
$myArray[$unknown] = …
```

PS: Add `ElementContent` for tracking flow through arrays

---

powershell/ql/lib/semmle/code/powershell/controlflow/ControlFlowGraph.qll
powershell/ql/lib/semmle/code/powershell/controlflow/internal/Completion.qll
powershell/ql/lib/semmle/code/powershell/controlflow/internal/ControlFlowGraphImpl.qll
powershell/ql/test/library-tests/controlflow/graph/Cfg.expected

Without this PR we get two `SimpleSuccessor`s out of the `foreach` loop in something like:
```powershell
foreach ($x in $xs) {
}
```
one that goes from the `foreach` itself to `$x` (which represents going into the loop), and one that goes from the `foreach` itself to the next statement (which represents the `foreach` being empty).
No control-flow element should have two successors with the same kind out of it. So this PR adds an `Emptiness` successor to distinguish between these two situations. This is the same strategy that C# uses.

PS: Add `Emptiness` completion to get rid of CFG inconsistencies

---

powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowPrivate.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowPublic.qll
powershell/ql/test/library-tests/dataflow/returns/test.expected
powershell/ql/test/library-tests/dataflow/returns/test.ps1
powershell/ql/test/library-tests/dataflow/returns/test.ql

This PR implements flow out of Powershell functions. For example:
```powershell
function Foo {
return 42
}
$x = Foo
Sink $x
```
To describe what's going on in this PR I'll first describe the necessary internal dataflow concepts, and then how we make these work in the context of Powershell.
There are three concepts we need to understand:
- `ReturnNode`
- `OutNode`
- `ReturnKind`
A `ReturnNode` is the node that represents the value to be returned from a callee. That is, in the above example, `42` is a `ReturnNode`. An `OutNode` is the node that represents the function call that's supposed to receive the return value when we leave the function. In the above example, that's `Foo` in `$x = Foo`.
The `Return`/`Out` naming scheme is less standard compared to the `Parameter`/`Argument` naming …

PS: Add flow out of functions

---

powershell/ql/lib/semmle/code/powershell/ArrayExpression.qll
powershell/ql/lib/semmle/code/powershell/StatementBlock.qll
powershell/ql/lib/semmle/code/powershell/controlflow/CfgNodes.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowPrivate.qll
powershell/ql/lib/semmle/code/powershell/internal/AstEscape.qll
powershell/ql/test/library-tests/dataflow/fields/test.expected
powershell/ql/test/library-tests/dataflow/fields/test.ps1

This PR adds flow through array expressions. That is, flow from `1` and `2` to this piece of syntax: `@(1, 2)`.
This is slightly harder than it looks because there can be an arbitrary set of statements inside `...` in `@(...)`. Luckily, we already have a way of computing which expressions are being returned from a list of statements. So this PR generalized that into a small parameterized module (internal for now) and reuses the logic to compute which expressions can end up in `@(...)`.
If it's clear which expressions this is, and in which order, we use an `ElementContent` with a specific index, and otherwise we use an `ElementContent` with an unknown index (see [here](https://github.com/microsoft/codeql/pull/113) for the terminology).

PS: Flow through arrays

---

powershell/ql/lib/semmle/code/powershell/BaseConstantExpression.qll
powershell/ql/lib/semmle/code/powershell/ConstantExpression.qll
powershell/ql/lib/semmle/code/powershell/HashTable.qll
powershell/ql/lib/semmle/code/powershell/StringConstantExpression.qll
powershell/ql/lib/semmle/code/powershell/controlflow/CfgNodes.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowPrivate.qll
powershell/ql/test/library-tests/dataflow/fields/test.expected
powershell/ql/test/library-tests/dataflow/fields/test.ps1

This PR adds flow through hash tables. That is, in situations like:
```powershell
$hash = @{
a = Get-TaintedData
b = 42
}
Sink $hash["a"]
```
This will be necessary for some upcoming work on supporting flow through `ValueFromPipelineByPropertyName` parameters.

PS: Flow through hash table creation, reads, and writes

---

powershell/ql/lib/semmle/code/powershell/ConvertExpr.qll
powershell/ql/lib/semmle/code/powershell/ParenExpression.qll
powershell/ql/lib/semmle/code/powershell/controlflow/CfgNodes.qll
powershell/ql/lib/semmle/code/powershell/controlflow/internal/ControlFlowGraphImpl.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowPrivate.qll
powershell/ql/lib/semmle/code/powershell/internal/ExplicitWrite.qll
powershell/ql/test/library-tests/dataflow/local/test.expected
powershell/ql/test/library-tests/dataflow/local/test.ps1

A pretty simple PR that adds flow through conversions (i.e., `$x = [string]42`) and parentheses (i.e., `$x = (42)`).

PS: Flow through conversions

---

powershell/ql/lib/semmle/code/powershell/Function.qll
powershell/ql/lib/semmle/code/powershell/NamedAttributeArgument.qll
powershell/ql/lib/semmle/code/powershell/ParamBlock.qll
powershell/ql/lib/semmle/code/powershell/Variable.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowPrivate.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/SsaImpl.qll
powershell/ql/test/library-tests/dataflow/pipeline/test.expected
powershell/ql/test/library-tests/dataflow/pipeline/test.ps1

This PR implements flow from pipeline arguments to `ValueFromPipelineByPropertyName` parameters. For example:
```powershell
function Process-Input {
Param([Parameter(ValueFromPipelineByPropertyName)] $x)
Sink $x
}
$x = Get-TaintedData
[pscustomobject]@{x = $x} | Process-Input
```
This is fairly simple given the machinery from https://github.com/microsoft/codeql/pull/119, https://github.com/microsoft/codeql/pull/121, and https://github.com/microsoft/codeql/pull/122:
1. From https://github.com/microsoft/codeql/pull/121 we get flow from `$x` to `@{x = $x}` with a store step that remembers that `x` is tainted.
2. From https://github.com/microsoft/codeql/pull/122 there is a flow step from `@{x = $x}` to `[pscustomobject]@{x = $x}`
3. From https://github.com/microsoft/codeql/pull/119 we get …

PS: Flow through `ValueFromPipelineByPropertyName` parameters

---

powershell/ql/lib/semmle/code/powershell/NamedAttributeArgument.qll
powershell/ql/lib/semmle/code/powershell/ScriptBlock.qll
powershell/ql/lib/semmle/code/powershell/Variable.qll
powershell/ql/lib/semmle/code/powershell/controlflow/CfgNodes.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowPrivate.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/SsaImpl.qll
powershell/ql/test/library-tests/dataflow/pipeline/test.expected
powershell/ql/test/library-tests/dataflow/pipeline/test.ps1

After merging https://github.com/microsoft/codeql/pull/123 I realized that `ValueFromPipelineByPropertyName` I learned that these variables can also be used to process a pipeline that's more than one element long. For example:
```powershell
function consume {
Param([Parameter(ValueFromPipelineByPropertyName)] $x)
process {
Write-Output $x
}
}
myArray | consume 
```
This outputs the property named `x` for each element in `myArray`.
In the previous PR I only allowed for `myArray` to be a single element.
Implementation-wise, this amounts to adding another `readStep` that reads off `ElementContent` before the `readstep` that reads off the `x` property.

PS: Allow for `ValueFromPipelineByPropertyName` to also read off an `ElementContent`

---

powershell/ql/lib/semmle/code/powershell/Function.qll
powershell/ql/lib/semmle/code/powershell/ScriptBlock.qll
powershell/ql/lib/semmle/code/powershell/controlflow/internal/Scope.qll
powershell/ql/lib/semmle/code/powershell/dataflow/TaintTracking.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/TaintTrackingImpl.qll
powershell/ql/test/TestUtilities/InlineFlowTestUtil.qll
powershell/ql/test/library-tests/dataflow/params/global.ps1
powershell/ql/test/library-tests/dataflow/params/test.expected

Currently, not all `Parameters` have a declaring function because we can have stuff like:
```
param($x)
Write-Output $x
```
at the top level (and these are then user-provided). A bunch of code depends on parameters always having an enclosing function, so this PR changes that to be the case.

PS: Global parameter support

---

powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowDispatch.qll
powershell/ql/test/library-tests/dataflow/params/global.ps1
powershell/ql/test/library-tests/dataflow/params/test.expected

Follow up to https://github.com/microsoft/codeql/pull/125. In order to have parameter positions (which are used to model SSA for parameters) we need to handle the case where a parameter belongs to an uncalled function. In particular, this happens when a parameter is a top-level parameter.
This PR ensures that these parameters always have positions.

PS: Include parameter positions for top level functions

---

powershell/ql/lib/semmle/code/powershell/controlflow/internal/Splitting.qll

hotfix for powershell not compiling

commenting out problematic powershell qll code

---

powershell/ql/lib/semmle/code/powershell/controlflow/internal/ControlFlowGraphImpl.qll
powershell/ql/lib/semmle/code/powershell/controlflow/internal/Splitting.qll
powershell/ql/test/library-tests/controlflow/graph/Cfg.expected

Some CodeQL languages (most notably C#, Ruby and Swift) use a technique called control-flow splitting to implement a more precise control-flow graph. I previously wrote about splitting [here](https://github.com/microsoft-sdl/codeql-queries/pull/2085).
In https://github.com/github/codeql/pull/17658 GitHub moved some of the logic for constructing split control-flow graphs into the existing shared control-flow graph library. As Powershell also uses this library this broke CI (see [here](https://github.com/microsoft/codeql/pull/129)).
This PR makes use of this new feature of the shared control-flow graph library in Powershell.

PS: Use the new shared control-flow splitting library

---

powershell/downgrades/c5191f89a6e3e8cea428b5c7326a06e335738533/old.dbscheme
powershell/downgrades/c5191f89a6e3e8cea428b5c7326a06e335738533/semmlecode.powershell.dbscheme
powershell/downgrades/c5191f89a6e3e8cea428b5c7326a06e335738533/upgrade.properties
powershell/extractor/Semmle.Extraction.PowerShell.Standalone/Options.cs
powershell/extractor/Semmle.Extraction.PowerShell.Standalone/Program.cs
powershell/extractor/Semmle.Extraction.PowerShell/Entities/Base/File.cs
powershell/extractor/Semmle.Extraction/Tuples.cs
powershell/ql/lib/semmle/code/powershell/File.qll
powershell/ql/lib/semmlecode.powershell.dbscheme
powershell/ql/lib/upgrades/802d5b9f407fb0dac894df1c0b4584f2215e1512/old.dbscheme
powershell/ql/lib/upgrades/802d5b9f407fb0dac894df1c0b4584f2215e1512/semmlecode.powershell.dbscheme
powershell/ql/lib/upgrades/802d5b9f407fb0dac894df1c0b4584f2215e1512/upgrade.properties

PowerShell has a peculiar feature of "implicit module imports".
From https://learn.microsoft.com/en-us/powershell/scripting/developer/module/importing-a-powershell-module?view=powershell-7.4#implicitly-importing-a-module-powershell-30:
> [...] modules are imported automatically when any cmdlet or function in the module is used in a command. This feature works on any module in a directory that is included in the value of the PSModulePath environment variable.
So when we see an invocation such as:
```
Foo 42
```
this may refer to a command defined in a file totally outside the source directory, and will be implicitly loaded into the current Powershell session.
To handle such scenarios this PR does several things:
- It adds extraction of the files inside the directories pointed to by the …

PS: Extract source files found via `PSModulePath`

---

powershell/codeql-extractor.yml
powershell/extractor/Semmle.Extraction.PowerShell.Standalone/Options.cs
powershell/tools/qltest.cmd

This PR is a follow-up to https://github.com/microsoft/codeql/pull/132 which I merged earlier this morning. In that PR, we started extracting Powershell files found via the `PSModulePath` environment variable, and added a CLI parameter to selectively disable this feature.
However, I forgot to add an official "extractor option" to control this. Without this extractor option it's not possible to disable `PSModulePath` extraction when running `codeql test run`. We need to disable `PSModulePath` extraction when running `codeql test run` to ensure that the tests are independent of the environment in which the tests are run.

PS: #132 follow-up

---

powershell/ql/lib/semmle/code/powershell/Command.qll
powershell/ql/lib/semmle/code/powershell/Variable.qll
powershell/ql/lib/semmle/code/powershell/VariableExpression.qll
powershell/ql/lib/semmle/code/powershell/controlflow/CfgNodes.qll
powershell/ql/lib/semmle/code/powershell/dataflow/flowsources/FlowSources.qll
powershell/ql/lib/semmle/code/powershell/dataflow/flowsources/Local.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowPublic.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/TaintTrackingPrivate.qll

Does what the title says 😂
This PR is mostly a grab bag of things that are needed for the first "real" Powershell query (a proper "tainted command" query).
The second commit is a drive-by fix that is necessary now that GitHub merged "spectulative flow" in https://github.com/github/codeql/pull/17663

PS: Add AST and CFG classes for operator `&` and add environment variable reads as local flow sources

---

powershell/ql/lib/semmle/code/powershell/controlflow/CfgNodes.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowPublic.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/TaintTrackingPrivate.qll
powershell/ql/test/library-tests/dataflow/local/flow.expected
powershell/ql/test/library-tests/dataflow/local/taint.expected
powershell/ql/test/library-tests/dataflow/local/test.ps1

This PR adds taint through string interpolation. That is, flow from `$x` to `"$x"`.

PS: Taint-flow through string interpolation

---

powershell/ql/lib/semmle/code/powershell/security/CommandInjectionCustomizations.qll
powershell/ql/lib/semmle/code/powershell/security/CommandInjectionQuery.qll
powershell/ql/src/queries/security/cwe-078/CommandInjection.qhelp
powershell/ql/src/queries/security/cwe-078/CommandInjection.ql
powershell/ql/src/queries/security/cwe-078/examples/command_injection.ps1
powershell/ql/test/qlpack.yml
powershell/ql/test/query-tests/security/cwe-078/CommandInjection/CommandInjection.expected
powershell/ql/test/query-tests/security/cwe-078/CommandInjection/CommandInjection.qlref
powershell/ql/test/query-tests/security/cwe-078/CommandInjection/test.ps1

This PR is a huge milestone. It adds the first proper taint-tracking production-quality query to Powershell 🎉
Specifically, it adds `powershell/command-injection` which is a "proper" version of the `powershell/tainted-command` query from the experimental folder.

PS: Add the first non-experimental query

---

powershell/ql/lib/semmle/code/powershell/Command.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowPrivate.qll
powershell/ql/test/library-tests/ast/parent.expected

I had missed a restriction on `c` in one of the cases of `storeStep`.

PS: Remove accidental CP

---

powershell/codeql-extractor.yml

Add support for CLI argument `--buildmode none` to the PowerShell extractor

PS: support buildmode none in extractor

---

cpp/ql/src/Diagnostics/ExtractorErrorMsft.ql
csharp/ql/src/Diagnostics/ExtractorErrorMsft.ql
go/ql/src/Diagnostics/ExtractorErrorMsft.ql
java/ql/src/Diagnostics/ExtractionErrorMsft.ql
javascript/ql/src/Diagnostics/ExtractionErrorMsft.ql
python/ql/src/Diagnostics/ExtractorErrorMsft.ql
ruby/ql/src/queries/diagnostics/ExtractorErrorMsft.ql
rust/ql/src/queries/diagnostics/ExtractorErrorMsft.ql
swift/ql/src/diagnostics/ExtractorErrorMsft.ql

Query for each language to detect files that failed to extract, along with the files' extractor errors. Plan is to incorporate this information into the CodeQL File Coverage project.

Failed Extraction Queries

---

powershell/ql/lib/semmle/code/powershell/dataflow/internal/FlowSummaryImpl.qll
powershell/ql/lib/semmle/code/powershell/typetracking/TypeTracking.qll
powershell/ql/lib/semmle/code/powershell/typetracking/internal/TypeTrackingImpl.qll

This was caused by two PRs on github/codeql:
- https://github.com/github/codeql/pull/18298
- https://github.com/github/codeql/pull/17787
On the GitHub side, it's the responsibility of the author of the changes to a shared library to make sure that the users of the shared library still works. However, as GitHub doesn't have PowerShell checks running in their CI it's not possible for them to do this. So we need to keep this up ourselves!
Luckily, such changes tend to be pretty trivial to fix. And indeed they are also easily fixable here.
Note that this PR will actually _not work_ until we bump our own fork as above PRs haven't been merged into our fork yet.
cc @dilanbhalla

Powershell: Fix dataflow library after GitHub changes

---

cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowPrivate.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll
csharp/ql/lib/semmle/code/csharp/dataflow/DataFlowStack.qll
csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowDispatch.qll
go/ql/lib/semmle/go/dataflow/internal/DataFlowPrivate.qll
java/ql/lib/semmle/code/java/dataflow/internal/DataFlowPrivate.qll
python/ql/lib/semmle/python/dataflow/new/internal/DataFlowDispatch.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll
shared/dataflow/codeql/dataflow/DataFlow.qll
shared/dataflowstack/codeql/dataflowstack/DataFlowStack.qll
shared/dataflowstack/codeql/dataflowstack/TaintTrackingStack.qll
swift/ql/lib/codeql/swift/dataflow/internal/DataFlowDispatch.qll

This changes the `DataFlowStack` library so that we don't depend on our own modifications to the shared dataflow library.
This has caused us quite a lot of pain in the past. Hopefully we can avoid doing such modifications in t he future.
Commit-by-commit review recommended:
- The first commit gets rid of the Microsoft modifications to the GitHub dataflow files. It turns out that we have resolved merge conflicts incorrect for some languages for almost 6 months. So many of the files were actually very very old that wasn't being kept up-to-date with the latest developments on the GitHub side 😅 Hopefully we should only have clean merges from now on!
- The second commit autoformats the `DataFlowStack` library to make the diff of the last file smaller
- The last commit does the actual …

Shared: Refactor `DataFlowStack`

---

java/ql/lib/semmle/code/java/dataflow/DataFlowStack.qll
shared/dataflowstack/codeql/dataflowstack/DataFlowStack.qll
shared/dataflowstack/codeql/dataflowstack/TaintTrackingStack.qll

I forgot to update the Java version of this file when I did https://github.com/microsoft/codeql/pull/157 🤦 This should make the Java file equivalent (but not identical!) to the C# one.
Additionally, there was a missing transitive closure that I forgot in https://github.com/microsoft/codeql/pull/157. I've attached this fix to this PR as well

Java: Update file that was forgotten in #157

---

javascript/ql/lib/semmle/javascript/dataflow/AdditionalFlowSteps.qll
javascript/ql/lib/semmle/javascript/dataflow/BackwardExploration.qll
javascript/ql/lib/semmle/javascript/dataflow/Configuration.qll
javascript/ql/lib/semmle/javascript/dataflow/DataFlow.qll
javascript/ql/lib/semmle/javascript/dataflow/ForwardExploration.qll
javascript/ql/lib/semmle/javascript/dataflow/TaintTracking.qll
javascript/ql/lib/semmle/javascript/dataflow/internal/BarrierGuards.qll
javascript/ql/lib/semmle/javascript/dataflow/internal/DataFlowPrivate.qll
javascript/ql/lib/semmle/javascript/dataflow/internal/FlowSteps.qll
javascript/ql/lib/semmle/javascript/explore/BackwardDataFlow.qll
javascript/ql/lib/semmle/javascript/explore/ForwardDataFlow.qll
javascript/ql/lib/semmle/javascript/security/CommonFlowState.qll
javascript/ql/lib/semmle/javascript/security/TaintedObject.qll
javascript/ql/lib/semmle/javascript/security/TaintedObjectCustomizations.qll
javascript/ql/lib/semmle/javascript/security/TaintedUrlSuffix.qll
javascript/ql/lib/semmle/javascript/security/TaintedUrlSuffixCustomizations.qll
javascript/ql/lib/semmle/javascript/security/dataflow/CodeInjectionQuery.qll
javascript/ql/lib/semmle/javascript/security/regexp/PolynomialReDoSCustomizations.qll
javascript/ql/lib/semmle/javascript/security/regexp/PolynomialReDoSQuery.qll
javascript/ql/lib/utils/test/ConsistencyChecking.qll

Deadline: January 2026 to migrate Microsoft JavaScript queries to new shared libraries. Temporarily removing deprecation warnings for smoother internal compilation/testing, high priority to migrate as soon as possible.

TEMPORARY: Remove JavaScript Deprecation Labels

---

cpp/ql/src/Likely Bugs/Leap Year/Adding365DaysPerYear.ql
cpp/ql/src/Likely Bugs/Leap Year/AntiPattern5InvalidLeapYearCheck.ql
cpp/ql/src/Likely Bugs/Leap Year/LeapYearConditionalLogic.ql
cpp/ql/src/Likely Bugs/Leap Year/UncheckedLeapYearAfterYearModification.ql
cpp/ql/src/Likely Bugs/Leap Year/UncheckedReturnValueForTimeFunctions.ql
cpp/ql/src/Likely Bugs/Leap Year/UnsafeArrayForDaysOfYear.ql
cpp/ql/src/Microsoft/Likely Bugs/Conversion/BadOverflowGuard.ql
cpp/ql/src/Microsoft/Likely Bugs/Drivers/IncorrectUsageOfRtlCompareMemory.ql
cpp/ql/src/Microsoft/Likely Bugs/SizeOfMisuse/ArgumentIsSizeofOrOperation.ql
cpp/ql/src/Microsoft/Likely Bugs/SizeOfMisuse/SizeOfConstIntMacro.ql
cpp/ql/src/Microsoft/Security/Cryptography/BannedEncryption.ql
cpp/ql/src/Microsoft/Security/Cryptography/BannedModesCAPI.ql
cpp/ql/src/Microsoft/Security/Cryptography/BannedModesCNG.ql
cpp/ql/src/Microsoft/Security/Cryptography/HardcodedIVCNG.ql
cpp/ql/src/Microsoft/Security/Cryptography/WeakKDFBannedHashAlgorithm.ql
cpp/ql/src/Microsoft/Security/Cryptography/WeakKDFLowIterationCount.ql
cpp/ql/src/Microsoft/Security/Cryptography/WeakKDFSmallKeyLength.ql
cpp/ql/src/Microsoft/Security/Cryptography/WeakKDFSmallSaltSize.ql
cpp/ql/src/Microsoft/Security/MemoryAccess/EnumIndex/UncheckedBoundsEnumAsIndex.ql
cpp/ql/src/Microsoft/Security/Protocols/HardCodedSecurityProtocol.ql
cpp/ql/src/Microsoft/Security/Protocols/UseOfDeprecatedSecurityProtocol.ql

Add microsoft-public namespace to query ids as _second_ component. So the convention is `<language>/<namespace>/<area>/etc.`

Add Microsoft-Public Namespace to Query IDs

---

powershell/ql/lib/semmle/code/powershell/controlflow/BasicBlocks.qll
powershell/ql/lib/semmle/code/powershell/controlflow/internal/ControlFlowGraphImpl.qll
powershell/ql/src/experimental/CommandInjection.ql
powershell/ql/src/queries/security/cwe-078/CommandInjection.ql
powershell/ql/src/queries/security/cwe-078/DoNotUseInvokeExpression.ql

GitHub added a couple of new predicates to the input module for computing the control-flow graph in https://github.com/github/codeql/pull/18497. This PR adds those required predicates to the input module. As a bonus, it also makes use of the new basic block library that they added in https://github.com/github/codeql/pull/18497 to reduce some code duplication 🎉
cc @dilanbhalla

PS: Fixup CFG library in preparation for 2.20.4

---

ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll

Predicate removed in https://github.com/microsoft/codeql/pull/157 is needed for our queries to compile.

resolving ruby df error

---

powershell/ql/lib/semmle/code/powershell/controlflow/BasicBlocks.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/SsaImpl.qll

https://github.com/github/codeql/pull/18696 broke PowerShell. This PR fixes it by matching the changes made to other languages
As is normal from these PRs, this will fail until we run it on 2.20.5.
As a bonus, this PR also fixes an compilation warning in SSA caused by https://github.com/github/codeql/pull/18729. There are a few other harder-to-fix warnings caused by that PR, but I'll delay those until later when I've got more time to look into the necessary changes
cc @dilanbhalla

PS: Match the changes from #18696

---

powershell/.gitignore
powershell/extractor/Microsoft.Extractor.Tests/Microsoft.Extractor.Tests.csproj
powershell/extractor/Semmle.Extraction.PowerShell.Standalone/Semmle.Extraction.PowerShell.Standalone.csproj
powershell/extractor/Semmle.Extraction.PowerShell/Entities/ScriptBlockEntity.cs
powershell/extractor/Semmle.Extraction.PowerShell/Semmle.Extraction.PowerShell.csproj
powershell/extractor/Semmle.Extraction/Semmle.Extraction.csproj
powershell/extractor/Semmle.Util/Semmle.Util.csproj

Also update dependencies.
Note: Due to changes in the Powershell SDK the RequiresPSSnapins property has been removed from the ScriptRequirements Property of the ScriptBlock object. I have opted to not change the dbscheme and instead just populate this value with a 0 for now, but that should be cleaned up.

Update .NET Version for Powershell Extractor to Net 9.0

---

powershell/ql/lib/semmle/code/powershell/ast/internal/CallExpr.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/ChildIndex.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/NamedBlock.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/Raw/ChildIndex.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/Raw/Function.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/Raw/Parameter.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/Raw/VariableExpression.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/Synthesis.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/TAst.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/Variable.qll
powershell/ql/lib/semmle/code/powershell/controlflow/CfgNodes.qll
powershell/ql/lib/semmle/code/powershell/controlflow/internal/ControlFlowGraphImpl.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowPrivate.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/SsaImpl.qll
powershell/ql/test/library-tests/ast/Statements/statements.expected
powershell/ql/test/library-tests/ast/parent.expected
powershell/ql/test/library-tests/controlflow/graph/Cfg.expected
powershell/ql/test/library-tests/controlflow/graph/consistency.expected
powershell/ql/test/library-tests/dataflow/local/flow.expected
powershell/ql/test/library-tests/dataflow/local/taint.expected
powershell/ql/test/library-tests/dataflow/local/test.ps1
powershell/ql/test/library-tests/dataflow/pipeline/test.expected
powershell/ql/test/library-tests/ssa/ssa.expected

More fixes after we merged https://github.com/microsoft/codeql/pull/178. This PR is mostly around fixing pipeline flow.
The only remaining ones now are value-from-pipeline-by-property-name flows.

PS: Fix more taint-tracking/dataflow regressions

---

powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowPrivate.qll
powershell/ql/test/library-tests/dataflow/params/test.expected
powershell/ql/test/library-tests/dataflow/params/test.ps1

Another missing flow found by Chanel!
Because PowerShell is case insensitive you can do stuff like:
```powershell
function Foo {
param($myParAm)
Write-Output $myParAm
}
Foo -MyPARAM "Hello"
```
In dataflow we need to "normalize" all the parameter names by lower-casing them. And apparently I had forgotten to lower-case the parameter names 🤦

PS: Fix parameter/argument name mapping for named parameters

---

powershell/ql/lib/semmle/code/powershell/ast/internal/ChildIndex.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/NamedBlock.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/Synthesis.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/Variable.qll
powershell/ql/lib/semmle/code/powershell/controlflow/CfgNodes.qll
powershell/ql/lib/semmle/code/powershell/controlflow/internal/Completion.qll
powershell/ql/lib/semmle/code/powershell/controlflow/internal/ControlFlowGraphImpl.qll
powershell/ql/lib/semmle/code/powershell/dataflow/Ssa.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowPrivate.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowPublic.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/FlowSummaryImpl.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/SsaImpl.qll
powershell/ql/test/library-tests/controlflow/graph/Cfg.expected
powershell/ql/test/library-tests/dataflow/fields/test.expected
powershell/ql/test/library-tests/dataflow/local/flow.expected
powershell/ql/test/library-tests/dataflow/local/taint.expected
powershell/ql/test/library-tests/dataflow/pipeline/test.expected
powershell/ql/test/library-tests/dataflow/pipeline/test.ps1
powershell/ql/test/library-tests/dataflow/returns/test.expected

This fixes the last remaining missing flows that were caused by https://github.com/microsoft/codeql/pull/178. The last ones are mostly concerned with pipeline-by-property-name parameters.

PS: Fix the last remaining missing flows after AST prettification

---

powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowPrivate.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/SsaImpl.qll
powershell/ql/test/library-tests/dataflow/local/flow.expected
powershell/ql/test/library-tests/dataflow/local/taint.expected

GitHub has been doing a number of changes to the shared SSA library (which PowerShell also uses). See, for example, https://github.com/github/codeql/pull/19147.
This PR makes the necessary PowerShell changes to make the PowerShell dataflow library work with 2.21.0
As always with these kinds of things, CI will be unhappy since these changes requires the shared libraries from 2.21.0.
cc @dilanbhalla

PS: Fixup SSA after GitHub's 2.21.0 changes

---

powershell/ql/lib/semmle/code/powershell/ApiGraphs.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/ChildIndex.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/Parameter.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/ScriptBlock.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/Synthesis.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/TypeExpression.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/Variable.qll
powershell/ql/lib/semmle/code/powershell/controlflow/CfgNodes.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowDispatch.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowPrivate.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowPublic.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/TaintTrackingPrivate.qll
powershell/ql/lib/semmle/code/powershell/frameworks/SystemManagementAutomation/model.yml
powershell/ql/lib/semmle/code/powershell/frameworks/data/internal/ApiGraphModelsSpecific.qll
powershell/ql/test/library-tests/ast/Blocks/blocks.expected
powershell/ql/test/library-tests/ast/Statements/statements.expected
powershell/ql/test/library-tests/ast/parent.expected
powershell/ql/test/library-tests/controlflow/graph/Cfg.expected
powershell/ql/test/library-tests/controlflow/graph/consistency.expected
powershell/ql/test/library-tests/dataflow/local/taint.expected
powershell/ql/test/library-tests/dataflow/mad/flow.expected
powershell/ql/test/library-tests/dataflow/mad/flow.ql
powershell/ql/test/library-tests/dataflow/mad/test.ps1
powershell/ql/test/library-tests/dataflow/params/test.expected
powershell/ql/test/library-tests/dataflow/pipeline/test.expected
powershell/ql/test/library-tests/ssa/ssa.expected

This PR fixes <s>two</s> three(!) PowerShell issues reported by @chanel-y:
Consider this example:
```psm
$executionContext.InvokeCommand.InvokeScript(...)
```
@chanel-y reported that the following use of API graphs didn't work:
```ql
from API::Node call
where
API::getTopLevelMember("executioncontext").getMember("invokecommand").getMethod("invokescript") =
call
select call, "..."
```
This was because we were missing two API edges:
- An edge from the top level (i.e., root) node to any use of an automatic variable such as `$executionContext`, and
- An edge from a qualifier to a member read such as `$executionContext.InvokeCommand`
With those two extra steps added, the above snippet works 🥳
In addition, I added two drive-by fixes:
- The first commit adds a location to the synthesized …

PS: Fix more Chanel-reported PowerShell issues

---

csharp/ql/lib/semmle/code/csharp/hashcons/HashCons.qll

This PR adds a hash-cons library for C# as requested by @ropwareJB.
The goal of a hash-consing library is to create an efficient way to compare two expressions without creating a quadratically sized relation. For example, if you were to check if two `VarAccess`es are "syntatically equal" you may create this relation:
```ql
predicate syntacticallySimilar(VarAccess va1, VarAccess va2) {
va1.getTarget() = va2.getTarget()
}
```
However, this relation would be of size `n^2` where `n` is the number of accesses of a variable in the program. For example, if you have this program:
```csharp
Use(x); // 1
Use(x); // 2
Use(x); // 3
```
this relation would include:
- A row in `syntacticallySimilar` that relates `x` on line 1 to `x` on line 1
- A row in `syntacticallySimilar` that relates `x` on line 1 …

C#: Add a hash-cons library for C#

---

powershell/ql/lib/semmle/code/powershell/ast/internal/FunctionBase.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/Synthesis.qll
powershell/ql/lib/semmle/code/powershell/dataflow/flowsources/Local.qll
powershell/ql/lib/semmle/code/powershell/frameworks/SystemConsole/model.yml
powershell/ql/test/query-tests/security/cwe-078/CommandInjection/CommandInjection.expected

Both the "top level arguments" and the "environment variable" local sources were never updated after https://github.com/microsoft/codeql/pull/178 was merged
This PR fixes these bugs.

PS: Fix a couple of missing local flow sources

---

.github/workflows/sync-main-tags.yml

Upon completion of auto/sync-main-pr pull request (syncs upstream commits), this workflow runs and also syncs upstream tags.

Sync Upstream Tags

---

powershell/ql/lib/semmle/code/powershell/ast/internal/Constant.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/Raw/Command.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/Synthesis.qll
powershell/ql/test/library-tests/ast/Arguments/arguments.expected
powershell/ql/test/library-tests/ast/Arguments/arguments.ps1
powershell/ql/test/library-tests/ast/Arguments/arguments.ql
powershell/ql/test/library-tests/ast/parent.expected

Previously, we did not handle switch arguments when constructing the AST.
This PR fixes this by synthesizing a Boolean `$true` argument so that a switch argument such as `Foo -MyFlag` looks the same (from the AST point-of-view) as `Foo -MyFlag:$true`.
Thanks for reporting this @chanel-y! 🙇 
Commit-by-commit review recommended.

PS: Proper AST support for switch arguments

---

powershell/ql/lib/semmle/code/powershell/ApiGraphs.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/Constant.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/Function.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/FunctionBase.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/Member.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/MemberExpr.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/Method.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/PropertyMember.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/Type.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/TypeDefinitionStmt.qll
powershell/ql/lib/semmle/code/powershell/controlflow/CfgNodes.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowDispatch.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowPrivate.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowPublic.qll
powershell/ql/lib/semmle/code/powershell/security/SqlInjectionCustomizations.qll
powershell/ql/lib/semmle/code/powershell/security/SqlInjectionQuery.qll
powershell/ql/src/experimental/UseOfReservedCmdletChar.ql
powershell/ql/src/queries/security/cwe-089/SqlInjection.qhelp
powershell/ql/src/queries/security/cwe-089/SqlInjection.ql
powershell/ql/src/queries/security/cwe-089/examples/SqlInjection.ps1
powershell/ql/test/library-tests/ast/Expressions/expressions.expected
powershell/ql/test/library-tests/ast/parent.expected
powershell/ql/test/query-tests/security/cwe-089/SqlInjection.expected
powershell/ql/test/query-tests/security/cwe-089/SqlInjection.qlref
powershell/ql/test/query-tests/security/cwe-089/test.ps1

This PR adds our second taint-tracking query. This one is for detecting SQL injections.
It's a pretty standard taint-tracking query from user-provided input to SQL execution commands. So far I've modelled:
1. [Invoke-Sqlcmd](https://learn.microsoft.com/en-us/powershell/module/sqlserver/invoke-sqlcmd)
2. Writes to [CommandText](https://learn.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlcommand.commandtext) which should cover both `System.Data.SqlClient` and `System.Data.OleDb`
3. Calls to the `sqlcmd` command-line utility
Commit-by-commit review is recommended as I also changed various library files to call `toLowerCase` more consistently on members

PS: Add SQL injection query

---

powershell/ql/lib/semmle/code/powershell/ast/internal/Internal.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/StringLiteral.qll
powershell/ql/test/library-tests/ast/Strings/String.ps1
powershell/ql/test/library-tests/ast/Strings/Strings.expected
powershell/ql/test/library-tests/ast/Strings/Strings.ql
powershell/ql/test/library-tests/ast/parent.expected

We don't really use the string literal class for anything in this public repo. However, the private repo had a query that used the `StringLiteral` class. And unlike the `StringConstExpr` class, the `StringLiteral` class was never exposed publicly in the user-facing AST.
This PR "exposes" the `StringLiteral` class. I write "exposes" because we actually just alias it to be `StringConstExpr` since `StringLiteral` contains a bunch of things that aren't actually string literals (commands, comments, etc.), and what you actually want when you look for `StringLiteral`s are probably the strings in single or double quotes. These are contained in the `StringLiteral` class along with a bunch of other string-like things. We should add an extensional from the extractor to distinguish `foo` from …

PS: Lift string literals to the public AST

---

csharp/ql/lib/semmle/code/csharp/security/dataflow/TaintedPathQuery.qll
csharp/ql/test/query-tests/Security Features/CWE-022/TaintedPath/TaintedPath.cs
csharp/ql/test/query-tests/Security Features/CWE-022/TaintedPath/TaintedPath.expected

This PR does three small improvements to the `cs/path-injection` query (each in their own commit):
- b40a43701cc99d3f9c48bd5c30f620d9129a079b does a very very small optimization. When you write:
```ql
predicate isSink(DataFlow::Node sink, FlowState state) {
sink instanceof Sink and
exists(state)
}
```
you're technically creating a cartesian product (CP) between all sinks and all states. This isn't a problem in this particular case since there are only 2 states (normalized and non-normalized) so the CP is very small. However, this can be a real problem if there are many states. Because of this we added a way to avoid this in https://github.com/github/codeql/pull/13851. The technical details aren't super important. However, it may be worth remembering that it's always safe to make the …

C#: Fix FPs (and a small FN) in `cs/path-injection`

---

cpp/ql/src/Likely Bugs/Leap Year/LeapYearConditionalLogic.qhelp
cpp/ql/src/Metrics/Classes/CNumberOfFunctions.qhelp
cpp/ql/src/Metrics/Classes/CSizeOfAPI.qhelp
java/ql/src/Metrics/RefTypes/TInheritanceDepth.qhelp
java/ql/src/Metrics/RefTypes/TNumberOfCallables.qhelp
java/ql/src/Metrics/RefTypes/TNumberOfFields.qhelp
java/ql/src/Metrics/RefTypes/TSizeOfAPI.qhelp

Several qhelp files have errors when running the `codeql generate query-help --format=markdown <qhelp-file` command
- Incorrect path to sample code
- Nested code inside `<ul>`, such as a second `<ul>` or a `<p>`
- This may be valid HTML, but is not supported by the qhelp file/throws an error when running the generate query-help command.

fix failing qhelp files

---

powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowPublic.qll

We may as well make this predicate available on dataflow nodes like it is on the AST nodes and on the control-flow nodes.

PS: Add `Node.getCallee` predicate on `DataFlow::CallNode`

---

powershell/ql/lib/semmle/code/powershell/ast/internal/Ast.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/CallExpr.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/Command.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/Parameter.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/Raw/Ast.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/Synthesis.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/Variable.qll
powershell/ql/lib/semmle/code/powershell/controlflow/internal/ControlFlowGraphImpl.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowPrivate.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/SsaImpl.qll

This PR fixes lots of performance issues in PowerShell.
On the given database I was running on this switched from "completely unanalyzable" to "finishes in 1.5 minute" 🎉
Commit-by-commit review recommended.

PS: Fix lots of performance problems

---

powershell/ql/lib/semmle/code/powershell/ast/internal/Raw/ChildIndex.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/Raw/CommandParameter.qll
powershell/ql/src/queries/security/cwe-250/InsecureExecutionPolicy.qhelp
powershell/ql/src/queries/security/cwe-250/InsecureExecutionPolicy.ql
powershell/ql/src/queries/security/cwe-250/examples/InsecureExecutionPolicy.ps1
powershell/ql/test/query-tests/security/cwe-250/InsecureExecutionPolicy.expected
powershell/ql/test/query-tests/security/cwe-250/InsecureExecutionPolicy.qlref
powershell/ql/test/query-tests/security/cwe-250/test.ps1

This PR adds a new PowerShell query `powershell/microsoft/public/insecure-execution-policy` which finds calls to `Set-ExecutionPolicy` that:
- Sets the execution policy to `Bypass` (["Nothing is blocked and there are no warnings or prompts."](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy?view=powershell-7.5#-executionpolicy) 😱)
- Sets the scope to more than `Process`.
- Sets the `-Force` flag.
I ran an initial draft query that omitted the restriction on the `Scope`, and I got **lots** of results that modified the execution policy only for the current process. So as a way to get _some_ version of this query merged I think it makes sense to initially make the query only alert on calls to `Set-ExecutionPolicy` that doesn't limit the …

PS: Add query for insecure uses of `Set-ExecutionPolicy`

---

powershell/ql/lib/semmle/code/powershell/ast/internal/ChildIndex.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/EnvVariable.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/Synthesis.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/TAst.qll
powershell/ql/lib/semmle/code/powershell/ast/internal/Variable.qll
powershell/ql/lib/semmle/code/powershell/controlflow/CfgNodes.qll
powershell/ql/lib/semmle/code/powershell/controlflow/internal/ControlFlowGraphImpl.qll
powershell/ql/lib/semmle/code/powershell/dataflow/Ssa.qll
powershell/ql/lib/semmle/code/powershell/dataflow/flowsources/Local.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowPrivate.qll
powershell/ql/lib/semmle/code/powershell/dataflow/internal/SsaImpl.qll
powershell/ql/lib/semmle/code/powershell/security/CommandInjectionCustomizations.qll
powershell/ql/test/library-tests/dataflow/global/test.expected
powershell/ql/test/library-tests/dataflow/global/test.ps1
powershell/ql/test/library-tests/dataflow/global/test.ql
powershell/ql/test/query-tests/security/cwe-078/CommandInjection/CommandInjection.expected
powershell/ql/test/query-tests/security/cwe-078/CommandInjection/test.ps1

This PR is an alternative to https://github.com/microsoft/codeql/pull/259. Instead of removing some of the environment variables as flow, we disable them all in the command injection query.
In addition, this PR implements global dataflow through environment variables so that we retain flow-through. This PR also adds a test that demonstrates this.
cc @chanel-y what do you think of this as an alternative to https://github.com/microsoft/codeql/pull/259?

PS: Global flow through environment variables

---

powershell/ql/lib/semmle/code/powershell/dataflow/internal/DataFlowPrivate.qll
powershell/ql/lib/semmle/code/powershell/security/SqlInjectionCustomizations.qll
powershell/ql/test/library-tests/dataflow/fields/test.expected
powershell/ql/test/library-tests/dataflow/global/test.expected
powershell/ql/test/library-tests/dataflow/mad/flow.expected
powershell/ql/test/library-tests/dataflow/params/test.expected
powershell/ql/test/library-tests/dataflow/pipeline/test.expected
powershell/ql/test/library-tests/dataflow/returns/test.expected
powershell/ql/test/query-tests/security/cwe-078/CommandInjection/CommandInjection.expected
powershell/ql/test/query-tests/security/cwe-089/SqlInjection.expected
powershell/ql/test/query-tests/security/cwe-502/UnsafeDeserialization.expected

... and also make the paths outputted in dataflow queries more readable.
This PR does two things (each in their own commit):
1. It removes environment variables as sources in the PowerShell SQL injection query. This matches the change we did in https://github.com/microsoft/codeql/pull/261/commits/b72af27e81e25fecaa79886e0444f40335326d9c for the command-line injection query.
2. It fixes a bug related to how we hide/unhide certain nodes in dataflow paths. The dataflow library has two "hooks" that decides which nodes to never show in a path (the `nodeIsHidden` predicate) and which nodes to always show in a path (the `neverSkipInPathGraph`). We had a bug in `nodeIsHidden` which always hid uses of local variables. This meant that paths were way too compressed to be readable. Furthermore, I …

PS: Remove environment variables from `powershell/microsoft/public/sql-injection`

---

powershell/ql/lib/semmle/code/powershell/security/SqlInjectionCustomizations.qll
powershell/ql/test/query-tests/security/cwe-089/SqlInjection.expected
powershell/ql/test/query-tests/security/cwe-089/test.ps1

The query was only considering the `-query` and `-inputfile` arguments, but not the aliases `-q` and `-i`. This resulted in both FPs and FNs.
This PR fixes these and also adds an example of the FP that's now fixed.

PS: Also handle `-q` and `-i` arguments in sql injection query
